<?php

/**
 * @file
 * Prevents admins from editing petitions outside of our workflow.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * If mongodb enabled, disable editing petition node form directly.
 */
function petitionsmongo2mysqlintegrity_form_petition_node_form_alter(&$form, &$form_state, $form_id) {
  global $user;

  $is_not_superuser = $user->uid !=1;

  if (petitions_data_mongo_reads_are_enabled() && $is_not_superuser) {
    // Remove ability to publish
    $form['options']['status']['#value'] = 1;
    $form['options']['#type'] = 'hidden';

    // Disable all fields on node edit form
    $form['#disabled'] = TRUE;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function petitionsmongo2mysqlintegrity_form_node_admin_content_alter(&$form, &$form_state, $form_id) {
  // Hide the publish option box on the petition node edit form.
  $form['admin']['options']['submit']['#validate'][] = 'petitionsmongo2mysqlintegrity_form_node_admin_content_validation';
}

/**
 * Throw error if petition node is published/unpublished via 'admin/content' form.
 */
function petitionsmongo2mysqlintegrity_form_node_admin_content_validation(&$form, &$form_state) {
  global $user;

  // Get list of selected items being acted upon.
  $selected = array();
  foreach ($form_state['values']['nodes'] as $choice) {
    if ($choice !== 0) {
      $selected[] = $choice;
    }
  }

  $options = $form['admin']['nodes']['#options'];
  $pub_options = array('publish', 'unpublish');
  $admin_link = l('petitions moderation page', 'admin/moderation-tools');

  $is_not_superuser = $user->uid !=1;
  
  if (petitions_data_mongo_is_on() && $is_not_superuser) {
    // Throw error if any of our actions are publish/unpublish and any selection is a petition.
    if (in_array($form_state['values']['operation'], $pub_options)) {
      foreach ($selected as $choice) {
        if ($options[$choice]['type'] == 'Petition') {
          form_set_error('petition_bypass_error', 'Sorry you cannot publish/unpublish petitions from this page. Please go to the new ' . $admin_link . '.');
          form_get_error($form);
        }
      }
    }
  }
}
