source 'https://rubygems.org'

group :development do

  # Sass, Compass and extensions.
  gem 'sass', '>= 3.3'           # Sass.
  gem 'sass-globbing', '1.1.0'  # Import Sass files based on globbing pattern.
  gem 'bourbon', '4.2.6'    # Import Bourbon SASS framework.
  gem 'neat', '1.7.2'           # Import Bourbon Neat grid framework

  # Dependency to prevent polling. Setup for multiple OS environments.
  # Optionally remove the lines not specific to your OS.
  # https://github.com/guard/guard#efficient-filesystem-handling
  gem 'rb-inotify', '~> 0.9', :require => false      # Linux
  gem 'rb-fsevent', :require => false                # Mac OSX
  gem 'rb-fchange', :require => false                # Windows

end
