<?php

/**
 * @file
 * Adds a "front" class to menu link for the front page.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function front_class_preprocess_links(&$variables) {
  if (isset($variables['attributes']['id']) && $variables['attributes']['id'] == 'main-menu-links') {
    $is_main_menu = (variable_get('menu_main_links_source', FALSE) == 'petitions-menu') ? TRUE : FALSE;
    if ($is_main_menu) {
      // For main menu, add "front" class to <front> link.
      $links = front_class_front_link($variables);
      $variables['links'] = $links;
    }
  }
}

/**
 * Find the <front> link. Add a "front" class to <li> to make it themable.
 *
 * @param array $variables
 *   Input parameter from front_class_preprocess_links().
 *
 * @return array $links
 *   $variable['links'] to override.
 */
function front_class_front_link(array $variables) {
  $links = $variables['links'];
  foreach ($links as $key => $link) {
    $is_front = front_class_is_front($link);
    if ($is_front) {
      // $links[$key] is used to determine <li class=$class>. Add 'front'.
      $original_key = $key;
      $new_key = $original_key . " front";
      $new_link = $link;
    }
  }
  // Rebuild $links array in same order it's already in.
  $new_links = array();
  foreach ($links as $key => $link) {
    if (isset($original_key) && $key == $original_key) {
      $new_links[$new_key] = $new_link;
    }
    else {
      $new_links[$key] = $link;
    }
  }
  return $new_links;
}

/**
 * Determine if $link is a link to <front>.
 *
 * @param array $link
 *   A link data array from front_class_preprocess_links().
 *
 * @return bool
 *   TRUE if the link refers to the site front page, or FALSE if not.
 */
function front_class_is_front(array $link) {
  $front = variable_get('site_frontpage', FALSE);
  $href = $link['href'];
  return ($front == $href) ? TRUE : FALSE;
}
