<?php
/**
 * @file
 * Install/update hooks for petitions_user_registration feature module.
 */

/**
 * PT-1261: Database cleanup for deleted login_destination module.
 */
function petitions_user_registration_update_7000() {
  if (db_table_exists('login_destination')) {
    db_drop_table('login_destination');
  }

  variable_del('login_destination_immediate_redirect');
  variable_del('login_destination_preserve_destination');
}
