<?php

/**
 * @file
 * This is the main module file for Petitions Signatures Display.
 */

/**
 * Implements hook_menu().
 */
function petitions_signatures_display_menu() {
  $items = array();

  $items['admin/config/petitions/signatures'] = array(
    'title' => 'Signatures Display',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('petitions_signatures_display_configure'),
    'access arguments' => array('administer site configuration'),
    'file' => 'petitions_signatures_display.admin.inc',
    'description' => "Configure signatures display.",
  );

  return $items;
}

/**
 * Returns [first name] [last initial].
 */
function petitions_signatures_display_fname_linitial($first_name = '', $last_name = '') {
  if ($first_name) {
    $name = ucfirst($first_name);
  }

  if ($last_name) {
    if ($name) {
      $name .= ' ' . ucfirst(mb_substr(trim($last_name), 0, 1)) . '.';
    }
    else {
      $name = ucfirst(mb_substr(trim($last_name), 0, 1)) . '.';
    }
  }

  return $name;
}

/**
 * Returns [first initial] [last initial].
 */
function petitions_signatures_display_finitial_linitial($first_name = '', $last_name = '') {
  if ($first_name) {
    $name = ucfirst(mb_substr(trim($first_name), 0, 1)) . '.';
  }

  if ($last_name) {
    if ($name) {
      $name .= ' ' . ucfirst(mb_substr(trim($last_name), 0, 1)) . '.';
    }
    else {
      $name = ucfirst(mb_substr(trim($last_name), 0, 1)) . '.';
    }
  }

  return $name;
}

/**
 * Returns formatted name.
 */
function petitions_signatures_display_style($username, $first_name = '', $last_name = '') {
  $function = variable_get('petitions_signatures_display_initials', 'petitions_signatures_display_fname_linitial');

  if ($first_name || $last_name) {
    $name = $function($first_name, $last_name);
  }
  else {
    $name = $username;
  }

  return $name;
}

/**
 * Returns an array including city, state, and abbreviated country.
 *
 * Invokes _perform_lookup() in wh_zipcodelookup.module.
 */
function petitions_signatures_display_location($zipcode = '') {
  if (module_exists('wh_zipcodelookup') && function_exists('_perform_lookup')) {
    $location = _perform_lookup($zipcode);
    return $location;
  }
  else {
    return;
  }
}

/**
 * Returns city and state formatted for display.
 *
 * Invokes _perform_lookup() in wh_zipcodelookup.module.
 */
function petitions_signatures_display_location_formatted($zipcode = '') {
  if (module_exists('wh_zipcodelookup') && function_exists('_perform_lookup')) {
    $location = petitions_signatures_display_location($zipcode);
    $city = $location[0]['city'];
    $state = $location[0]['state'];
    if ($city && $state) {
      $formatted_location = $city . ', ' . $state;
    }
    elseif ($city && !$state) {
      $formatted_location = $city;
    }
    elseif (!$city && $state) {
      $formatted_location = $state;
    }
    return $formatted_location;
  }
  else {
    return;
  }
}

/**
 * Default location fields display.
 */
function petitions_signatures_display_city_state(&$form) {
  // Attach wh_zipcodelookup.js.
  if (module_exists('wh_zipcodelookup')) {
    $form['#attached']['js'][] = drupal_get_path('module', 'wh_zipcodelookup') . '/wh_zipcodelookup.js';
  }
  return $form;
}

/**
 * Display disabled location fields.
 */
function petitions_signatures_display_city_state_disabled(&$form) {
  // Disable city and state fields.
  $form['profile_main']['field_city']['#disabled'] = TRUE;
  $form['profile_main']['field_state']['#disabled'] = TRUE;
  // Attach wh_zipcodelookup.js.
  if (module_exists('wh_zipcodelookup')) {
    $form['#attached']['js'][] = drupal_get_path('module', 'wh_zipcodelookup') . '/wh_zipcodelookup.js';
  }
  // Add form validation.
  $form['#validate'][] = 'petitions_signatures_display_location_validate';
  return $form;
}

/**
 * Hide location fields from display.
 */
function petitions_signatures_display_city_state_hidden(&$form) {
  // Hide city and state fields.
  $form['profile_main']['field_city']['#type'] = 'hidden';
  $form['profile_main']['field_state']['#type'] = 'hidden';
  // Add form validation.
  $form['#validate'][] = 'petitions_signatures_display_location_validate';
  return $form;
}

/**
 * Implements hook_form_alter().
 */
function petitions_signatures_display_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_register_form' || $form_id == 'user_profile_form') {
    $function = variable_get('petitions_signatures_display_account_location', 'petitions_signatures_display_city_state');
    $form += $function($form);
  }
}

/**
 * Form validation callback.
 */
function petitions_signatures_display_location_validate($form, &$form_state) {
  $zipcode = $form_state['values']['profile_main']['field_zip'][LANGUAGE_NONE][0]['value'];
  $location = petitions_signatures_display_location($zipcode);
  $city = $location[0]['city'];
  $state = $location[0]['state'];
  if ($location[0]['country'] == 'us') {
    $country = 'United States';
  }
  else {
    $country = $form_state['values']['profile_main']['field_country'][LANGUAGE_NONE][0]['value'];
  }

  $values = array(
    'field_city' => $city,
    'field_state' => $state,
    'field_country' => $country,
  );

  foreach ($values as $key => $value) {
    form_set_value($form['profile_main'][$key], array(LANGUAGE_NONE => array(0 => array('value' => $value))), $form_state);
  }
}

/**
 * Alter the display of user profile location fields.
 */
function petitions_signatures_display_profile2_view_alter(&$build, $type) {
  $display = variable_get('petitions_signatures_display_profile_location', 'petitions_signatures_display_profile_user_city_state');
  if ($display == 'petitions_signatures_display_profile_db_city_state') {
    $zipcode = $build['field_zip']['#items'][0]['value'];
    $location = petitions_signatures_display_location($zipcode);
    $city = $location[0]['city'];
    $state = $location[0]['state'];
    if ($location[0]['country'] == 'us') {
      $country = 'United States';
    }
    else {
      $country = $build['field_country']['#items'][0]['value'];
    }

    if ($city) {
      $build['field_city'][0]['#markup'] = $city;
    }
    else {
      unset($build['field_city']);
    }

    if ($state) {
      $build['field_state'][0]['#markup'] = $state;
    }
    else {
      unset($build['field_state']);
    }

    if ($build['field_country']['#items'][0]['value']) {
      $build['field_country'][0]['#markup'] = $country;
    }
  }
}
