<?php
/**
 * @file
 * This file is necessary to reset the configuration settings on uninstall.
 */

/**
 * Implements hook_uninstall().
 */
function petitions_signatures_display_uninstall() {
  variable_del('petitions_signatures_display_initials');
  variable_del('petitions_signatures_display_account_location');
  variable_del('petitions_signatures_display_profile_location');
  variable_del('petitions_signatures_display_signature_location');
}

/**
 * Implements hook_install().
 */
function petitions_signatures_display_install() {
  db_query("UPDATE {system} SET weight = 100 WHERE name = 'petitions_signatures_display'");
}

/**
 * Implements hook_update_last_removed().
 */
function petitions_signatures_display_update_last_removed() {
  return 7001;
}
