<?php
/**
 * @file clean_mongo.module
 */

 /**
  * Implements hook_help().
  */
 // todo

/**
 * Clean up and filter for mongo queries.
 * 
 * @param $params
 *   String or array to be filtered.
 */
function clean_mongo_query($params) {
  
  // Store original request
  $orig_params = $params;
  
  // Drop into an array for processing of not an array.
  if(!is_array($params)) {
    $params = array($params);
  }
  
  
  foreach($params as $key => $target) {
    if(!is_numeric($target)) {
      $params[$key] = _clean_mongo_query($target);
    }
  }
  
  // If the original request was not an array, return the string.
  if(!is_array($orig_params)) {
    return $params[0];
  }
  
  return $params;
}


/**
 * @param string $string
 *  String to sanitize.
 *
 * @return
 *  Sanitized string.
 */
function _clean_mongo_query($string) {
  // Filter for all of these terms.
  $filters = array(
    'shellcode',
    'nativeHelper',
    'nativehelper',
    '{',
    '}',
    '(',
    ')',
    'Array',
  );
  
  foreach ($filters as $filter) {
    $string = str_replace($filter, '', $string);
  }
  
 return $string; 
}
