<?php
/**
 * @file
 * This is the main module file for GSA Authentication.
 */

/**
* Implements hook_api_key_manager_name_for_key().
*/
function gsa_auth_api_key_manager_name_for_key($key) {
  // @todo implement this hook.
  // Returning dummy data for now.
  return 'We the People (EXAMPLE)';
}

/**
 * Implements hook_api_key_manager_url_for_key().
 */
function gsa_auth_api_key_manager_url_for_key($key) {
  // @todo implement this hook.
  // Returning dummy data for now.
  return 'https://petitions.whitehouse.gov';
}