<?php

/**
 * @file
 * api_authentication.module
 *
 * Provides authentication methods for the Petitions API.
 */

/**
 * Implements hook_services_authentication_info().
 */
function api_authentication_services_authentication_info() {
  return array(
    'file'             => 'api_authentication.inc',
    'title'            => t('API authentication'),
    'description'      => t('Key-based API authentication'),
    'authenticate_call' => '_api_authentication_authenticate_call',
  );
}
