<?php
/**
 * @file
 * This is the main module file for petitions_data.
 */

// @todo Remove this after mongo is turned off before version 7.x-3.0 release.
require_once __DIR__ . '/petitions_data.mongo2mysql.inc';

/**
 * Implements hook_menu().
 */
function petitions_data_menu() {
  $items = array();

  $items['admin/config/services/petitions_data'] = array(
    'title' => 'Petitions Data Settings',
    'description' => 'Configure settings for the Petitions Data module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('petitions_data_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_form().
 *
 * Administration form.
 */
function petitions_data_form($form, &$form_state) {
  global $base_url;
  $form['petitions_data_petitions_website_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Petitions Website URL'),
    '#default_value' => variable_get('petitions_data_petitions_website_url', $base_url),
    '#description' => t('Enter a website URL used to generate links to petitions site.'),
    '#required' => FALSE,
  );
  $form['petitions_data_petitions_api_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Petitions API URL'),
    '#default_value' => variable_get('petitions_data_petitions_api_url', $base_url),
    '#description' => t('Enter an API URL used to generate links to API.'),
    '#required' => FALSE,
  );
  $form['petitions_data_limits'] = array(
    '#type' => 'fieldset',
    '#title' => t('Resource limits'),
    '#description' => t('Limit maximum resultset size for resources'),
  );

  if (module_exists('petitions_signatures_display')) {
    $form['petitions_data_signatures_display_names'] = array(
      '#type' => 'checkbox',
      '#title' => t('Display names using Petitions Signatures Display settings'),
      '#default_value' => variable_get('petitions_data_signatures_display_names', 0),
      '#description' => t('Format names returned by the Signatures method in the same manner in which they are displayed on account profiles and in Petition signatures as configured by the <a href="@url">Petitions Signatures Display module</a>.', array('@url' => '/admin/config/petitions/signatures')),
      '#required' => FALSE,
    );
    $form['petitions_data_signatures_display_locations'] = array(
      '#type' => 'checkbox',
      '#title' => t('Display locations using Petitions Signatures Display settings'),
      '#default_value' => variable_get('petitions_data_signatures_display_locations', 0),
      '#description' => t('Format locations returned by the Signatures method in the same manner in which they are displayed on account profiles and in Petition signatures as configured by the <a href="@url">Petitions Signatures Display module</a>.', array('@url' => '/admin/config/petitions/signatures')),
      '#required' => FALSE,
    );
  }

  return system_settings_form($form);
}

/**
 * Implements hook_flush_caches().
 */
function petitions_data_flush_caches() {
  return array('cache_petitions_petitions');
}

/**
 * Clear the cache_petitions_petitions cache.
 */
function petitions_data_clear_caches() {
  cache_clear_all('*', 'cache_petitions_petitions', TRUE);
}

/**
 * Clear cache of specified petition_id.
 *
 * @param string $petition_id
 *   A hexidecimal petition ID.
 */
function petitions_data_clear_cached_petition($petition_id) {
  // Assuming a cache clear is more expensive than a get, we check
  // if it is cached before clearing.
  if (cache_get("petition:{$petition_id}", 'cache_petitions_petitions')) {
    cache_clear_all("petition:{$petition_id}", 'cache_petitions_petitions');
  }
}

/**
 * Freshen cache of specified petition_id.
 *
 * @param string $petition_id
 *   A hexidecimal petition ID.
 */
function petitions_data_freshen_cached_petition($petition_id) {
  // Clear the petition from cache.
  petitions_data_clear_cached_petition($petition_id);

  // Reload the petition into cache.
  petitions_data_mongo2mysql_get_petition($petition_id);
}

/**
 * Gets a "nice URL" from a full URL.
 *
 * @param string $full_url
 *   The full URL, e.g., "https://example.com/petition/some-title/as1d2vy6".
 *
 * @return string
 *   The corresponding "nice URL", e.g., "petition/some-title/as1d2vy6".
 */
function petitions_data_get_nice_url_from_full_url($full_url) {
  // The "nice URL" is just the URL path component without the leading forward
  // slash (/).
  $url_parts = parse_url($full_url);
  $nice_url = substr($url_parts['path'], 1);
  return $nice_url;
}

/**
 * Checks to see if a petition is open and not expired.
 *
 * @param string $petition_id
 *   A hexidecimal petition ID.
 *
 * @return bool
 *   Returns TRUE if the petition is open and not expired.
 */
function petitions_data_petition_is_open($petition_id) {
  $petition = petitions_data_mongo2mysql_get_petition($petition_id);

  // Confirm that the petition exists.
  if (empty($petition)) {
    return FALSE;
  }

  // Confirm that the petition has not been removed.
  if ($petition['status'] !== 'open') {
    return FALSE;
  }

  return TRUE;
}

/**
 * Sanitizes database output.
 *
 * Removes characters that break XML validation and replaces non-English
 * characters with x's.
 *
 * @param string $string
 *   The raw input string.
 *
 * @return string
 *   The XML-safe output string.
 */
function petitions_data_sanitize_output($string) {
  // Make the string XML-safe by removing unacceptable Unicode characters.
  // @see http://stackoverflow.com/questions/12229572/php-generated-xml-shows-invalid-char-value-27-message
  $string = preg_replace('/[^\x{0009}\x{000a}\x{000d}\x{0020}-\x{D7FF}\x{E000}-\x{FFFD}]+/u', '', $string);

  // Replace non-English characters with x's.
  // @see http://stackoverflow.com/questions/3654879/remove-non-english-characters-php
  $string = preg_replace('/[^\00-\255]+/u', 'x', $string);

  // Remove potential XSS attempts.
  $string = filter_xss($string);

  return $string;
}
