<?php
/**
 * @file
 * This is the main module file for petitions_data.
 */

/**
 * Implements hook_menu().
 */
function petitions_data_menu() {
  $items = array();

  $items['admin/config/services/petitions_data'] = array(
    'title' => 'Petitions Data Settings',
    'description' => 'Configure settings for the Petitions Data module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('petitions_data_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_form().
 *
 * Administration form.
 */
function petitions_data_form($form, &$form_state) {
  $form['petitions_data_petitions_website_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Petitions Website URL'),
    '#default_value' => variable_get('petitions_data_petitions_website_url', $base_url),
    '#description' => t('Enter a website URL used to generate links to petitions site.'),
    '#required' => FALSE,
  );
  $form['petitions_data_petitions_api_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Petitions API URL'),
    '#default_value' => variable_get('petitions_data_petitions_api_url', $base_url),
    '#description' => t('Enter an API URL used to generate links to API.'),
    '#required' => FALSE,
  );
  $form['petitions_data_limits'] = array(
    '#type' => 'fieldset',
    '#title' => t('Resource limits'),
    '#description' => t('Limit maximum resultset size for resources'),
  );

  if (module_exists('petitions_signatures_display')) {
    $form['petitions_data_signatures_display_names'] = array(
      '#type' => 'checkbox',
      '#title' => t('Display names using Petitions Signatures Display settings'),
      '#default_value' => variable_get('petitions_data_signatures_display_names', 0),
      '#description' => t('Format names returned by the Signatures method in the same manner in which they are displayed on account profiles and in Petition signatures as configured by the <a href="@url">Petitions Signatures Display module</a>.', array('@url' => '/admin/config/petitions/signatures')),
      '#required' => FALSE,
    );
    $form['petitions_data_signatures_display_locations'] = array(
      '#type' => 'checkbox',
      '#title' => t('Display locations using Petitions Signatures Display settings'),
      '#default_value' => variable_get('petitions_data_signatures_display_locations', 0),
      '#description' => t('Format locations returned by the Signatures method in the same manner in which they are displayed on account profiles and in Petition signatures as configured by the <a href="@url">Petitions Signatures Display module</a>.', array('@url' => '/admin/config/petitions/signatures')),
      '#required' => FALSE,
    );
  }

  return system_settings_form($form);
}

/**
 * Makes a string XML-safe by removing unacceptable Unicode characters.
 *
 * @see http://www.phpwact.org/php/i18n/charsets#xml
 *
 * @param string $string
 *   The raw input string.
 *
 * @return string
 *   The XML-safe output string.
 */
function petitions_data_make_xml_safe($string) {
  $string = preg_replace('/[^\x{0009}\x{000a}\x{000d}\x{0020}-\x{D7FF}\x{E000}-\x{FFFD}]+/u', '', $string);
  return $string;
}
