<?php

/**
 * @file
 * Provides validations for Services according to Whitehouse API Standards.
 */

/**
 * Implements hook_services_resources().
 */
function api_validations_services_resources() {
  $resources = array();

  $resources['validations'] = array(
    'operations' => array(
      'index' => array(
        'callback' => '_api_validations_resource_index',
        'args' => array(
          array(
            'name' => 'api_key',
            'optional' => FALSE,
            'type' => 'string',
            'description' => t('The API key.'),
            'source' => array('param' => 'api_key'),
          ),
          array(
            'name' => 'petition_id',
            'optional' => TRUE,
            'type' => 'string',
            'description' => t('Optionally filter by Petition ID.'),
            'source' => array('param' => 'petition_id'),
          ),
          array(
            'name' => 'mock',
            'optional' => TRUE,
            'type' => 'int',
            'description' => 'When set to 1, this will cause the service to return a mock response.',
            'default value' => 0,
            'source' => array('param' => 'mock'),
          ),
        ),
        'access callback' => 'services_access_menu',
        'documentation callback' => '_api_validations_index_doc',
        'documentation versions' => array(1000),
        'file' => 'api_validation.inc',
      ),
    ),
  );

  return $resources;
}

/**
 * Callback for Services validations index method.
 */
function _api_validations_resource_index($api_key, $petition_id, $mock) {
  global $base_url;

  // Return mock response.
  if ($mock) {
    $response = json_decode(_api_validations_mock_response('index'));
    return $response;
  }

  // Check for the required key.
  if (empty($api_key) || !api_key_manager_valid_key($api_key)) {
    $status_code = 401;
    $developer_message = t("Invalid key.");
    $user_message = t("The key provided is not valid.");
    return api_errors_throw_error($status_code, $developer_message, $user_message);
  }

  $query = db_select('signature_validations', 'v')
    ->fields('v', array('vid', 'email', 'signature_id', 'petition_id'))
    // Only get records for the provided key.
    ->condition('signature_source_api_key', $api_key);

  // Filter by optional parameters.
  !empty($petition_id) AND $query = $query->condition('petition_id', $petition_id);

  // Limit the query to some maximum.
  $query->range(0, 10000);

  // Get all results in an array.
  $results = $query->execute()->fetchAllAssoc('vid', PDO::FETCH_ASSOC);

  // Error out if there aren't any results.
  if (empty($results)) {
    $status_code = 400;
    $developer_message = t("Not found.");
    $user_message = t("There were no results for this request.");
    $more_info = "http://github.com/whitehouse/petitions/issue/[PLACEHOLDER]";
    $error_code = "[GitHub issue number]";
    return api_errors_throw_error($status_code, $developer_message, $user_message, $more_info, $error_code);
  }

  $response = array(
    'metadata' => array(
      'responseInfo' => array(
        'status' => 200,
        'developerMessage' => t('OK'),
      ),
      'resultset' => array(
        'count' => count($results),
      ),
      // The query can be useful during development.
      // 'query' => $query->execute()->getQueryString(),
    ),
    'results' => $results,
  );

  return $response;
}

/**
 * Documentation callback for index method.
 */
function _api_validations_index_doc() {
  $element = array(
    '#name' => t('Index'),
    '#path' => '/validations',
    '#weight' => 1,
    '#description' => t('Returns a list of validations matching passed parameters.'),
    '#request_url' => url(variable_get('petitions_data_petitions_api_url', '') . '/v1/validations.json?key=asY1k9uCQY7Hg8MCBaa', array('absolute' => TRUE)),
    '#response' => _api_validations_mock_response('index'),
    '#auth' => TRUE,
  );

  return $element;
}

/**
 * Returns a mock response for validations methods.
 */
function _api_validations_mock_response($method) {
  switch ($method) {
    case 'index':
      $file = 'api_validations_index.response.json';
      break;

  }
  $response = file_get_contents(__DIR__ . '/example_validations/' . $file);
  return $response;
}
