<?php

/**
 * @file
 * api_validations.module
 *
 * Provides validations for Services according to Whitehouse API Standards.
 */

/**
 * Implements hook_services_resources().
 */
function api_validations_services_resources() {
  $resources = array();

  $resources['validations'] = array(
    'operations' => array(
      'index' => array(
        'callback' => '_api_validations_resource_index',
        'args' => array(
          array(
            'name' => 'key',
            'type' => 'string',
            'description' => t('The source API key.'),
            'source' => array('param' => 'key'),
          ),
          array(
            'name' => 'petition_id',
            'optional' => TRUE,
            'type' => 'string',
            'description' => t('Optionally filter by Petition ID.'),
            'source' => array('param' => 'petition_id'),
          ),
        ),
        'access callback' => 'services_access_menu',
        'documentation callback' => '_api_validations_index_doc',
        'file' => 'api_validation.inc',
      ),
    ),
  );

  return $resources;
}

/**
 * Documentation callback for index method.
 */
function _api_validations_index_doc() {
  module_load_include('inc', 'api_validations');

  $element = array(
    '#name' => t('Index'),
    '#path' => '/validations',
    '#weight' => 1,
    '#description' => t('Returns a list of validations matching passed parameters.'),
    '#request_url' => url(variable_get('petitions_data_petitions_api_url', '') . '/v1/validations.json?key=asY1k9uCQY7Hg8MCBaa', array('absolute' => TRUE)),
    '#response' => _api_validations_mock_response('index'),
    '#auth' => TRUE,
  );

  return $element;
}
