<?php
/**
 * @file
 * The signature queue system.
 *
 * Provides SignaturesQueue class, configuration for signatures queues, and a
 * queue monitoring dashboard.
 */

/**
 * Implements hook_menu().
 */
function signatures_queue_menu() {
  $items = array();

  $items['admin/config/system/signatures-queue'] = array(
    'title' => 'Petition Signatures Queue',
    'description' => 'Overview of petition signatures queue system',
    'page callback' => 'signatures_queue_overview',
    'access arguments' => array('monitor queues'),
    'file' => 'signatures_queue.pages.inc',
  );
  $items['admin/config/system/signatures-queue/monitor'] = array(
    'title' => 'Monitor',
    'description' => 'Monitor signature queues',
    'page callback' => 'signatures_queue_monitor_page',
    'access arguments' => array('monitor queues'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
    'file' => 'signatures_queue.pages.inc',
  );
  $items['admin/config/system/signatures-queue/settings'] = array(
    'title' => 'Settings',
    'description' => 'Configure signature queues',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('signatures_queue_configure'),
    'access arguments' => array('administer queues'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 3,
    'file' => 'signatures_queue.admin.inc',
  );
  $items['admin/config/development/generate/signatures'] = array(
    'title' => 'Generate signatures',
    'description' => 'Generate signature records in signatures queues',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('signatures_queue_generate_form'),
    'access arguments' => array('administer queues'),
    'weight' => 6,
    'file' => 'signatures_queue.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function signatures_queue_permission() {
  return array(
    'administer queues' => array(
      'title' => t('Administer signatures queue'),
    ),
    'monitor queues' => array(
      'title' => t('Monitor signatures queue'),
    ),
  );
}

/**
 * Generate dummy data in signature queues.
 */
function signatures_queue_generate($queue_name, $number = 10, $delete_first = FALSE) {
  // Remove all items first.
  if ($delete_first) {
    $queue = SignaturesQueue::get($queue_name);
    // There is no harm in trying to recreate existing.
    $queue->createQueue();
    $count = $queue->numberOfItems();
    $queue->deleteQueue();
    $text = t('@name: This queue was deleted with @count items remaining in it.',
      array('@name' => $queue_name, '@count' => $count)
    );
    drupal_set_message($text);
  }

  // Generate items.
  $queue = SignaturesQueue::get($queue_name);
  // There is no harm in trying to recreate existing.
  $queue->createQueue();
  for ($i = 0; $i < $number; $i++) {
    $item = SignaturesQueue::getDummyItem($queue_name);
    $queue->createItem($item);
  }
  $text = t('@name: @number items have been created.',
    array('@name' => $queue_name, '@number' => $number)
  );
  drupal_set_message($text);

}

/*
 * Implements hook_shunt().
 */
function signatures_queue_shunt() {
  return array(
    'signature_queue_receive_new_signatures' => t('A shunt for the "Receive new signatures" workflow.'),
    'signature_queue_initiate_signature_validation' => t('A shunt for the "Initiate signature validation" workflow.'),
    'signature_queue_receive_signature_validation' => t('A shunt for the "Receive signature validation" workflow.'),
    'signature_queue_preprocess_signatures' => t('A shunt for the "Preprocess signatures" workflow.'),
    'signature_queue_process_signatures' => t('A shunt for the "Process signatures" workflow.'),
    'signature_queue_archive_signatures' => t('A shunt for the "Archive signatures" workflow.'),
  );
}

/**
 * Gets an array of queue names.
 *
 * Note: Real queues are named something_queue. The tables listed here that
 * don't end in the suffix "_queue" aren't actually queues. Conceptually
 * they're part of the "signatures queue" in the sense that these are holding
 * bins where signatures go before they're done being processed and counted.
 * But they're not DrupalQueue queues.
 *
 * @return array
 *   Array of signature queues and descriptions keyed by queue name.
 */
function signatures_queue_get_queue_names() {
  return array(
    'signatures_submitted_queue' => t('Queue submissions received via API POST requests or form submissions by unauthenticated users.'),
    'signatures_pending_validation_queue' => t('Retrieve petitons from signatures_submitted_queue, send a validation email, then move the pending signature here.'),
    'signatures_validated_queue' => t('When a user clicks a validation link received via email, store the secret validation key here.'),
    'signatures_validated' => t('Move records from signatures_validated_queue to here for processing.'),
    'signatures_pending_validation' => t('Move records from signatures_pending_validation_queue to here for processing.'),
    'signatures_orphans' => t('When processing validated signatures, records in signatures_validated that do not have matching records in signatures_pending_validation are orphans.'),
  );
}
