<?php
/**
 * @file
 * This is the main module file for Shunt.
 */

/**
 * Implements hook_menu().
 */
function shunt_menu() {
  $items = array();

  $items['admin/settings/shunt'] = array(
    'title' => 'Shunt',
    'description' => 'Notify other modules to fail gracefully.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('shunt_admin_settings'),
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * Callback for admin/settings/shunt.
 *
 * @see system_settings_form
 */
function shunt_admin_settings() {
  // Generic shunt.
  $form['shunt_is_enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t('shunt_is_enabled'),
    '#default_value' => variable_get('shunt_is_enabled', FALSE),
    '#description' => t('Trip (enable) the shunt to notify modules to fail gracefully.'),
  );

  // Add checkboxes for custom shunts.
  $custom_shunts = module_invoke_all('shunt');
  foreach ($custom_shunts as $custom_shunt => $description) {
    $form[$custom_shunt] = array(
      '#type' => 'checkbox',
      '#title' => $custom_shunt,
      '#default_value' => variable_get($custom_shunt, FALSE),
      '#description' => t($description),
    );
  }

  return system_settings_form($form);
}
