<?php

/**
 * @file
 * Provides signatures for Services according to Whitehouse API Standards.
 */

/**
 * Implements hook_services_resources().
 */
function api_signatures_services_resources() {
  $resources = array();

  $resources['signatures'] = array(
    'operations' => array(
      'create' => array(
        'help' => 'Creates a signature',
        'file' => array(
          'type' => 'inc',
          'module' => 'api_signatures',
          'name' => 'api_signatures',
        ),
        'callback' => '_api_signatures_resource_create',
        'access callback' => 'services_access_menu',
        'args' => array(
          array(
            'name' => 'signature',
            'type' => 'array',
            'description' => 'The signature array',
            'source' => 'data',
            'optional' => FALSE,
          ),
        ),
      ),
    ),
  );

  return $resources;
}
