<?php

/**
 * @file
 * Provides signatures for Services according to Whitehouse API Standards.
 */

/**
 * Implements hook_services_resources().
 */
function api_signatures_services_resources() {
  $resources = array();

  $resources['signatures'] = array(
    'operations' => array(
      'create' => array(
        'help' => 'Creates a signature',
        'file' => array(
          'type' => 'inc',
          'module' => 'api_signatures',
          'name' => 'api_signatures',
        ),
        'callback' => '_api_signatures_resource_create',
        'access callback' => 'services_access_menu',
        'args' => array(
          array(
            'name' => 'signature',
            'type' => 'array',
            'description' => t('The signature array. The following array keys are required: signature_source_api_key, petition_id, email, first_name, last_name. Accepted request content types: application/json, application/xml, text/xml, application/x-www-form-urlencoded, application/vnd.php.serialized'),
            'source' => 'data',
            'optional' => FALSE,
          ),
        ),
        'documentation callback' => '_api_signatures_create_doc',
      ),
    ),
  );

  return $resources;
}

/**
 * Documentation callback for create method of signatures resource.
 */
function _api_signatures_create_doc() {
  $element = array(
    '#name' => t('Create'),
    '#auth' => TRUE,
    '#path' => '/signatures',
    '#weight' => 2,
    '#description' => t('Send an independently gathered signature to a petition.'),
    '#request_url' => url(variable_get('petitions_data_petitions_api_url', '') . '/v1/signatures', array('absolute' => TRUE)),
    '#request_data' => file_get_contents(__DIR__ . '/examples/' . 'api_signatures_create.request.json'),
    '#response' => file_get_contents(__DIR__ . '/examples/' . 'api_signatures_create.response.json'),
    '#auth' => TRUE,
  );

  return $element;
}
